CREATE OR REPLACE PACKAGE PKG_OBJ_USUARIOS AS

    -- Actualizar descripción por ID
    PROCEDURE ACTUALIZAR_DESCRIPCION (
        p_id IN USERS.ID%TYPE,
        p_descripcion IN USERS.DESCRIPCION%TYPE
    );

    -- Obtener usuario como OBJ_USUARIO
    FUNCTION OBTENER_USUARIO (
        p_id IN USERS.ID%TYPE
    ) RETURN OBJ_USUARIO;

END PKG_OBJ_USUARIOS;
/

CREATE OR REPLACE PACKAGE BODY PKG_OBJ_USUARIOS AS

    PROCEDURE ACTUALIZAR_DESCRIPCION (
        p_id IN USERS.ID%TYPE,
        p_descripcion IN USERS.DESCRIPCION%TYPE
    )
    AS
BEGIN
UPDATE USERS
SET DESCRIPCION = p_descripcion
WHERE ID = p_id;

IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20001, 'Usuario no encontrado con ID: ' || p_id);
END IF;

COMMIT;
END ACTUALIZACION_DESCRIPCION;


    FUNCTION OBTENER_USUARIO (
        p_id IN USERS.ID%TYPE
    ) RETURN OBJ_USUARIO
    AS
        v_obj OBJ_USUARIO;
BEGIN
SELECT OBJ_USUARIO(ID, NOMBRE, EMAIL, DESCRIPCION)
INTO v_obj
FROM USERS
WHERE ID = p_id;

RETURN v_obj;
EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN NULL;
END OBTENER_USUARIO;

END PKG_OBJ_USUARIOS;
/
